-- Annule le give arme dans les veh de police mais sa prend trop de MS
--Citizen.CreateThread(function()
--    while true do
--        Citizen.Wait(0)
--        DisablePlayerVehicleRewards(PlayerId())
--    end
--end)